### ISSUE TITLE
please update npm package

### ISSUE THREAD

**Issue by silentcloud** [istanbuljs/istanbul-lib-hook#10]
install error: 

![default](https://cloud.githubusercontent.com/assets/1698185/24135073/058e42c2-0e43-11e7-82fd-799a1352c239.png)

npm info :

![image](https://cloud.githubusercontent.com/assets/1698185/24135097/24ff7220-0e43-11e7-8584-f459f8296283.png)

**Comment by popomore** [comment]
Why I can't find the release on Github?

**Comment by bcoe** [comment]
@popomore @silentcloud this should already be fixed; there was a bad release which was immediately rolled back.

**Comment by popomore** [comment]
No, changing the latest tag can't fix this dependency error. Can you release another version revert to 1.0.0?

**Comment by dead-horse** [comment]
istanbul-api@1.1.4 required istanbul-lib-hook@^1.0.3, so change the latest tag of istanbul-lib-hook can not fix this problem

**Comment by popomore** [comment]
try `npm i istanbul@1.1.0-alpha.1` to reproduce this error.

**Comment by dead-horse** [comment]
`npm dist-tag add istanbul-api@1.1.1 latest` can fix this temporary

**Comment by bcoe** [comment]
@dead-horse @popomore try now, I've rolled back the tag on istanbul-api.

@jamestalmage any chance you could accelerate giving me publication permissions to append-transform? this error was caused by lerna failing to publish append-transform.

**Comment by valerybodak** [comment]
+1. I have the same issue today when I run npm install for my ReactNative project. My npm version is **4.4.1**

_npm ERR! notarget No compatible version found: append-transform@^0.4.3
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.4.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'istanbul-lib-hook'
npm ERR! notarget_

PLEASE FIX IT.

**Comment by benhalverson** [comment]
@bcoe Whatever you changed fixed the error I was also seeing. 
```├─┬ karma-coverage-istanbul-reporter@0.2.3
│ └─┬ istanbul-api@1.1.1
│   ├── fileset@2.0.3
│   ├── istanbul-lib-coverage@1.0.1
│   ├─┬ istanbul-lib-hook@1.0.0
│   │ └─┬ append-transform@0.4.0
```

**Comment by bcoe** [comment]
@valerybodak this should now be fixed; can you confirm.

**Comment by abrahamks** [comment]
yes it is fixed @bcoe

**Comment by valerybodak** [comment]
@bcoe Yes. It is fixed. Thank you.

**Comment by bcoe** [comment]
@valerybodak @abrahamks @benhalverson @silentcloud, etc. FYI; I'm deprecating these repos in favor of [this monorepo](https://github.com/istanbuljs/istanbuljs) which should help issues be spread out over less repos.
