### ISSUE TITLE
Change the name.

### ISSUE THREAD

**Issue by jamestalmage** [istanbuljs/istanbul-lib-hook#4]
`istanbul-lib-hook` implies something `istanbul` specific.

`pirates` and `wrap-require` have been suggested.

**Comment by gotwarlost** [comment]
I personally like `shanghai` :)

Note that this repo also provides a mechanism for hooking in `vm.runInThisContext`, `vm.createScript` etc. and this PR https://github.com/gotwarlost/istanbul/pull/465 in the istanbul repo adds more stuff to it. We should be careful about scope in a common library that is anticipated to be used in multiple places.

I also need to have a conversation with the open source gurus in my company @gyehuda and @davglass  so they can provide some input about the licensing stuff if the code were to be moved out of this org, renamed etc. Unless you guys are ok leaving it in this org and just renaming the repo.

link: https://github.com/bcoe/nyc/issues/70 as context for the new folks added to the thread

**Comment by ariporad** [comment]
@gotwarlost: actually, in the linked thread, it was suggested that it was out of scope for this project, so I'm going to put it in a different one. You're welcome to do whatever you want, but I would rather that istanbul just used the new module, as the whole point is to make everything work together. (Also, I suggested the name pirates, and I'd kind of like to use it, if you don't mind).

Also, can I have permission to modify and include your code from this repo in the new project? (with attribution)

**Comment by gotwarlost** [comment]
Yeah, I thought you might want to do something like this which is why I involved the open-source gurus who can figure out the details for us.

**Comment by ariporad** [comment]
@gotwarlost: ok, thanks!

So, @gyehuda and @davglass: what steps should I take to get the ok to use and modify (Actually, I think in practice I would more just be taking ideas from) this repo? I plan to release it under MIT, if that helps. I can also just look at this implementation and then build my own, if that would be easier. Thanks!

**Comment by jamestalmage** [comment]
I personally don't have a problem leaving it here. I just want something widely known and widely adopted. 

> We should be careful about scope in a common library that is anticipated to be used in multiple places.

Agreed. I take it you are suggesting `vm.runInThisContext`, and `vm.createScript` would be out of scope? I am not so sure. They all seem to serve the same goal (interjecting transforms). I think the reason most people only hook `require` is that `vm` is not widely known.

**Comment by ariporad** [comment]
@jamestalmage: no, of you read the linked thread, I want to add some stuff which focuses on making various require hooks work well together, which is out of scope here

**Comment by jamestalmage** [comment]
I have been monitoring (and participating) in the linked thread from the beginning.

I don't think "making various require hooks work well together", is at all out of scope for a library that installs require hooks. 

I also do not have a problem moving it. The important part of my sentence was "I just want something widely known and widely adopted".

**Comment by gotwarlost** [comment]
I guess we don't need this any more. We already have `pirates` and `append-transform` as the underlying layers on which hooks are built.
