### ISSUE TITLE
include-all-sources option runs code / slows down coverage

### ISSUE THREAD

**Issue by gdborton** [istanbuljs/istanbul-lib-hook#6]
Setting the `include-all-sources` option in `.istanbul.yml` makes istanbul `require` source files, which then run outside of any global setup that might be done in test runs.  It also means that any require statements are also followed, leading to slower coverage times.

I was able to fix this locally by setting a flag `process.env.istanbul_missing_files = true;` in the missing file logic in `istanbul-api`, and checking for it in istanbul-lib-hook.  This made our coverage twice as fast (several minutes saved).

**istanbul-api/run-cover.js**

``` javascript
process.env.istanbul_missing_files = true;
if(missingFiles.length > 0) {
  missingFiles.forEach(function(file) {
    require(file);
    if (!cov[file]) {
      cov[file] = instrumenter.lastFileCoverage().data;
    }
  }
}
// { more missing file logic... }
process.env.istanbul_missing_files = undefined;
```

**istanbul-lib-hook/hook.js**

``` javascript
Module._extensions[ext] = function (module, filename) {
  var _compile = module._compile;
  module._compile = function (code, filename) {
    var ret = fn(code, filename);
    if (postLoadHook) {
      postLoadHook(filename);
    }
    if (!process.env.istanbul_missing_files) { // only return the compiled source if we aren't looking at missing files.
      return _compile.call(module, ret.code, filename);
    }
  };
  originalLoaders[ext](module, filename);
};
```

I'm certain that this isn't the right way to do this, but it's a start...

**Comment by gotwarlost** [comment]
So I guess what you are trying to do is to only instrument the code and stuff the blank coverage into the coverage object and not require the file?

This is a good idea and I will find a better way to implement this. Thanks for the input!
