### ISSUE TITLE
Update `append-transform`

### ISSUE THREAD

**Issue by blakeembrey** [istanbuljs/istanbul-lib-hook#7]
See https://github.com/TypeStrong/ts-node/issues/183#issuecomment-241302682. I recently updated `ts-node` to follow the same require extension transform pattern as `pirates` and the hook I had added originally to `instabul`. The problem now is that falling back to the "next loader", which in this case is `istanbul`, results in the old version of `append-transform` that threw errors instead of loading via `.js`.

**Comment by alinhle** [comment]
I hope the PR is getting merged soon, though it didn't seem to have caught any attention! :-(

**Comment by bcoe** [comment]
@cvle @blakeembrey sorry for dropping this on the floor for such a long time.

I've released a new version of `istanbul-lib-hook`; it is now available in the latest version of `istanbul-api`, and is available in the next release of `nyc`:

`npm i nyc@next`
